module.exports = {
	PRIORITY: {
		DEFENSE: 100,
		REFILL_SPAWN: 90,
		HARVEST: 80,
		REFILL_TOWER: 70,
		BUILD: 50,
		REPAIR: 40,
		UPGRADE: 20,
	},

	SPAWN_PRIORITY: {
		DEFENDER: 100,
		GENERALIST: 50,
	},

	MAX_HARVESTERS_PER_SOURCE: 3,
	REPAIR_HP_THRESHOLD: 0.8,

	BACKLOG_TICKS_THRESHOLD: 5,
	GENERALIST_RATIO: { work: 1, carry: 1, move: 1 },
	DEFENDER_BODY: [ATTACK, ATTACK, MOVE, MOVE],
	MAX_CREEPS: 8,
	MIN_ENERGY_TO_SPAWN: 200,

	LOG_ENABLED: true,
};
